@startuml
interface Sujet {
    + enregistrerObservateur(Observateur)
    + supprimerObservateur(Observateur)
    + notifierObservateurs()
}

interface Observateur {
    + actualiser()
}

class VueArborescence {
    + actualiser()
}

class VueDiagramme {
    + actualiser()
}

class ModelArborescence {
    - observateurs : ArrayList<Observateur>
    + ModelArborescence(FileComposite)
    + enregistrerObservateur(Observateur)
    + supprimerObservateur(Observateur)
    + notifierObservateurs()
}

class ModelDiagramme {
    - observateurs : ArrayList<Observateur>
    + ModelDiagramme()
    + ajouterClasse(Classe)
    + supprimerClasse(Classe)
    + enregistrerObservateur(Observateur)
    + supprimerObservateur(Observateur)
    + notifierObservateurs()
}

class ControllerArborescence {
    - model : ModelArborescence
    + ControllerArborescence()
    + handle(MouseEvent)
}

class ControllerDiagramme {
    - model : ModelDiagramme
    + ControllerDiagramme()
    + handle(MouseEvent)
}

class FileComposite {
    # file : File
    + FileComposite(File)
}

class Fichier {
    # file : File
    + FileComposite(File)
}

class Repertoire {
    # file : File
    + FileComposite(File)
}

class Classe {
    - type : String
    - nom: String
    - package : String
    - attributs : HashMap<String, int>
    - methodes : HashMap<String, int>
    - coordonnées : int[]
    + Classe(String, String, String, ArrayList<String>, ArrayList<String>)
    + getType() : String
    + getNom() : String
    + getPackage() : String
    + getAttributs() : ArrayList<String>
    + getMethodes() : ArrayList<String>
    + getCoordonnées()
    + setCoordonnées(int, int)
}

class Analyseur {
    + Analyseur()
    + analyseClasse(String)
    - getHeader(Class<?>)
    - getConstructors(Class<?>)
    - getMethods(Class<?>)
    - getModifiers(int)
}

Sujet <|-- ModelArborescence
Sujet <|-- ModelDiagramme

Observateur <|.. VueArborescence
Observateur <|.. VueDiagramme

VBox <|-- VueArborescence
Pane <|-- VueDiagramme

FileComposite <|-- Fichier
FileComposite <|-- Repertoire

ModelDiagramme "1" <-- "0..*" Classe : classes
ModelArborescence "1" <-- "1..*" FileComposite : arborescence

EventHandler <|.. ControllerArborescence
EventHandler <|.. ControllerDiagramme
@enduml