@startuml
interface Sujet {
    + enregistrerObservateur(Observateur)
    + supprimerObservateur(Observateur)
    + notifierObservateurs()
}

interface Observateur {
    + actualiser()
}

class VueArborescence {
    + actualiser()
}

class VueDiagramme {
    + actualiser()
}

class ModelArborescence {
    - arborescence : FileComposite
    - observateurs : ArrayList<Observateur>
    + ModelArborescence(FileComposite)
    + updateArborescence()
    + enregistrerObservateur(Observateur)
    + supprimerObservateur(Observateur)
    + notifierObservateurs()
}

class ModelDiagramme {
    - classes : ArrayList<Classe>
    - observateurs : ArrayList<Observateur>
    + ModelDiagramme()
    + ajouterClasse(Classe)
    + supprimerClasse(Classe)
    + enregistrerObservateur(Observateur)
    + supprimerObservateur(Observateur)
    + notifierObservateurs()
}

class ControllerArborescence {
    - model : ModelArborescence
    + ControllerArborescence()
    + handle(MouseEvent)
}

class ControllerDiagramme {
    - model : ModelDiagramme
    + ControllerDiagramme()
    + handle(MouseEvent)
}

class FileComposite {
    # file : File
    + {abstract} FileComposite(File)
    + {abstract} actualiser()
    + {abstract} getContenu() : List<FileComposite>
    + {abstract} isDirectory() : boolean
    + toString() : String
}

class Fichier {
    # file : File
    + FileComposite(File)
    + actualiser()
    + getContenu() : List<FileComposite>
    + isDirectory() : boolean
}

class Repertoire {
    # file : File
    + FileComposite(File)
    + actualiser()
    + getContenu() : List<FileComposite>
    + isDirectory() : boolean
}

class Classe {
    - type : String
    - nom: String
    - package : String
    - attributs : HashMap<String, int>
    - methodes : HashMap<String, int>
    - coordonnées : int[]
    + Classe(String, String, String, ArrayList<String>, ArrayList<String>)
    + getType() : String
    + getNom() : String
    + getPackage() : String
    + getAttributs() : ArrayList<String>
    + getMethodes() : ArrayList<String>
    + getCoordonnées()
    + setCoordonnées(int, int)
}

class Analyseur {
    + Analyseur()
    + analyseClasse(String)
    - getHeader(Class<?>)
    - getConstructors(Class<?>)
    - getMethods(Class<?>)
    - getModifiers(int)
}

Sujet <|.. ModelArborescence
Sujet <|.. ModelDiagramme

Observateur <|.. VueArborescence
Observateur <|.. VueDiagramme

VBox <|-- VueArborescence
Pane <|-- VueDiagramme

FileComposite <|-- Fichier
FileComposite <|-- Repertoire

ModelDiagramme "1" --> "0..*" Classe : classes
ModelArborescence "1" --> "1..*" FileComposite : arborescence
ModelDiagramme "1" --> "1" Analyseur : analyseur

EventHandler <|-- ControllerArborescence
EventHandler <|-- ControllerDiagramme
@enduml